---
version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 173.17.0.0/16
services:
  mongo:
    image: mongo:3.6
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      app_net:
        ipv4_address: 173.17.0.2
  urlshortener:
    image: crebollar79/sbtexercise:urlshort
    hostname: shortener
    container_name: shortener
    depends_on:
      - mongo
    ports:
      - "9000:9000"
    environment:
      MONGO_DB: "mongodb://mongo:27017/shortener"
      SECRET_KEY_ENV: "QCY?tAnfk?aZ?iwrNwnxIlR6CTf:G3gf:90Latabg@5241AB`R5W:1uDFN];Ik@n"
    networks:
      app_net:
        ipv4_address: 173.17.0.3